@ECommerceOrderApi_HostAddress = http://localhost:5268

GET {{ECommerceOrderApi_HostAddress}}/weatherforecast/
Accept: application/json

###

@ECommerceOrderApi_HostAddress = https://localhost:7071

### Yeni Sipariş Oluşturma
POST {{ECommerceOrderApi_HostAddress}}/api/v1/orders
Content-Type: application/json

{
  "userId": "12345678-1234-1234-1234-123456789012",
  "items": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 2,
      "quantity": 1
    }
  ]
}

###

### Sipariş Detayları Getirme
GET {{ECommerceOrderApi_HostAddress}}/api/v1/orders/1

###

### Hatalı Sipariş Oluşturma - Eksik Kullanıcı ID
POST {{ECommerceOrderApi_HostAddress}}/api/v1/orders
Content-Type: application/json

{
  "items": [
    {
      "productId": 1,
      "quantity": 2
    }
  ]
}

###

### Hatalı Sipariş Oluşturma - Geçersiz Miktar
POST {{ECommerceOrderApi_HostAddress}}/api/v1/orders
Content-Type: application/json

{
  "userId": "12345678-1234-1234-1234-123456789012",
  "items": [
    {
      "productId": 1,
      "quantity": 0
    }
  ]
}

###

### Hatalı Sipariş Oluşturma - Olmayan Ürün
POST {{ECommerceOrderApi_HostAddress}}/api/v1/orders
Content-Type: application/json

{
  "userId": "12345678-1234-1234-1234-123456789012",
  "items": [
    {
      "productId": 999,
      "quantity": 1
    }
  ]
}

###
